# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GameOfThronesApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'IceAndFireKit'


  # Pods for GameOfThronesApp

  target 'GameOfThronesAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'IceAndFireKit'

  end

  target 'GameOfThronesAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
